version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../backend/.
      dockerfile: dockerfile
    image: backend
    container_name: backend
    ports:
      - "4000:4000"
